### ISSUE TITLE
refused with 400 Invalid SDP For Speech Service

### ISSUE THREAD

**Issue by nacartwright** [MayamaTakeshi/mrcp_server#32]
Testing with Cisco contact center and keep getting 400 invalid SDP for speech service. 

Here is the invite that get sent from the client: 

INVITE sip:tts@10.89.232.46:5060;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 10.89.219.175:5065;branch=z9hG4bKfoU1jitTDKnsi1gGzHHzFA~~4746
Max-Forwards: 70
To: <sip:tts@10.89.232.46>
From: <sip:voiceBrowser@10.89.219.175>;tag=dsf2e4866e
Call-ID: EA819A72-0178-1000-4000-001125AE2A68
CSeq: 100 INVITE
Content-Length: 336
Contact: <sip:voiceBrowser@10.89.219.175:5065;transport=tcp>
Content-Type: application/sdp
Call-Info: <sip:10.89.219.175:5065>;method="NOTIFY;Event=telephone-event;Duration=2000"
Allow-Events: telephone-event
Allow: INVITE, INFO, BYE, CANCEL, ACK, UPDATE
User-Agent: Cisco-UCCX

v=0
o=- 123 456 IN IP4 10.89.219.175
s=Unified Contact Center Express 12.5.1.11001-348
c=IN IP4 10.89.219.175
t=0 0
m=audio 52790 RTP/AVP 0 96
a=rtpmap:0 pcmu/8000
a=rtpmap:96 telephone-event/8000
a=fmtp:96 0-15
a=recvonly
a=mid:1
m=application 9 TCP/MRCPv2
a=setup:active
a=connection:new
a=fmtp:96 0-15
a=resource:speechsynth
a=cmid:1

**Comment by MayamaTakeshi** [comment]
The only real MRCP client I ever tested with was FreeSWITCH.
I used sipp to simulate the Cisco-UCCX with the above INVITE. 
The message caused an assertion failure
```
2021-04-20 07:48:41.835 error: sip_server (sip_server.js:193) AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(m.length >= 4)
```

 because it was expecting a line in the format:
```
  m=<media> <port> <proto> <fmt>
```
but it got this instead:
```
  m=application 9 TCP/MRCPv2 
```
(so fmt is missing)

Is this really what Cisco-UCCX is sending?
Here's what FS sends for comparison:
```
  m=application 9 TCP/MRCPv2 1
```
The RFC6787 (MRCP v2) says this:
_To remain backwards compatible with conventional SDP usage, the format field of the "m="  line MUST have the arbitrarily selected value of "1"._

So, Cisco-UCCX would be wrong.

But anyway, I tried changing the sipp scenario to send the expected line
```
  m=application 9 TCP/MRCPv2 1
```
but this didn't cause the '400' error:
```
(base) takeshi:tmp$ sudo ngrep -dany -q -W byline '.' 'port 8070'
interface: any
filter: ( port 8070 ) and (ip || ip6)
match: .

T 127.0.0.1:5050 -> 127.0.0.1:8070 [AP] #4
INVITE sip:tts@127.0.0.1:8070;transport=tcp SIP/2.0.
Via: SIP/2.0/TCP 127.0.0.1:5050;branch=z9hG4bK-16130-1-0.
Max-Forwards: 70.
To: sip:tts@127.0.0.1.
From: sip:voiceBrowser@127.0.0.1;tag=dsf2e4866e.
Call-ID: 1-16130@127.0.0.1.
CSeq: 100 INVITE.
Content-Length:   347.
Contact: sip:voiceBrowser@127.0.0.1:5050;transport=tcp.
Content-Type: application/sdp.
Call-Info: sip:127.0.0.1:5050;method="NOTIFY;Event=telephone-event;Duration=2000".
Allow-Events: telephone-event.
Allow: INVITE, INFO, BYE, CANCEL, ACK, UPDATE.
User-Agent: Cisco-UCCX.
.
v=0.
o=- 123 456 IN IP4 127.0.0.1.
s=Unified Contact Center Express 12.5.1.11001-348.
c=IN IP4 127.0.0.1.
t=0 0.
m=audio 6000 RTP/AVP 0 96.
a=rtpmap:0 pcmu/8000.
a=rtpmap:96 telephone-event/8000.
a=fmtp:96 0-15.
a=recvonly.
a=mid:1.
m=application 9 TCP/MRCPv2 1.
a=setup:active.
a=connection:new.
a=fmtp:96 0-15.
a=resource:speechsynth.
a=cmid:1.


T 127.0.0.1:8070 -> 127.0.0.1:5050 [AP] #6
SIP/2.0 100 Trying.
Via: SIP/2.0/TCP 127.0.0.1:5050;branch=z9hG4bK-16130-1-0;received=127.0.0.1.
To:  <sip:tts@127.0.0.1>.
From:  <sip:voiceBrowser@127.0.0.1>;tag=dsf2e4866e.
Call-ID: 1-16130@127.0.0.1.
CSeq: 100 INVITE.
Content-Length: 0.
.


T 127.0.0.1:8070 -> 127.0.0.1:5050 [AP] #8
SIP/2.0 200 OK.
Via: SIP/2.0/TCP 127.0.0.1:5050;branch=z9hG4bK-16130-1-0;received=127.0.0.1.
To:  <sip:tts@127.0.0.1>;tag=262157.
From:  <sip:voiceBrowser@127.0.0.1>;tag=dsf2e4866e.
Call-ID: 1-16130@127.0.0.1.
CSeq: 100 INVITE.
Contact:  <sip:mrcp_server@127.0.0.1:8070>.
Content-Type: application/sdp.
Content-Length: 296.
.
v=0.
o=mrcp_server 1212606071011504954 4868540303632141964 IN IP4 127.0.0.1.
s=-.
c=IN IP4 127.0.0.1.
t=0 0.
m=application 8888 TCP/MRCPv2 1.
a=setup:passive.
a=connection:new.
a=channel:1-16130@127.0.0.1@speechsynth.
a=cmid:1.
m=audio 10000 RTP/AVP 0.
a=rtpmap:0 PCMU/8000.
a=sendonly.
a=mid:1.
```

Please confirm if Cisco is really sending invalid m= line without <fmt>
```
  m=application 9 TCP/MRCPv2 
```
if yes, since the fmt is actually not necessary for processing and it is just required by RFC6787 to be proper SDP I will modify the code to accept m=application lines without it.

**Comment by nacartwright** [comment]
Correct – they only have three parameters in the M line at least for the initial invite. Also, noticed that \r\n doesn’t work with messages coming from CCX either.

var lines = s.split("\n") <-- UCCX is a Linux system so it does not use \r\n
        var media_id = -1
        lines.forEach(line => {
                var key = line.slice(0,1)
                var val = line.slice(2)

                switch(key) {
                case 'c':
                        var c = val.split(" ")
                        assert(c.length == 3)
                        sdp.connection = {
                                ip: c[2]
                        }
                        break
                case 'm':
                        var m = val.split(" ")
                        assert(m.length >= 4)
                        media_id++
                        sdp.media[media_id] = {
                                type: m[0],
                                port: parseInt(m[1]),
                                protocol: m[2],
                                payloads: m.slice(3),


Nathan A. Cartwright
Technical Lead
CDW | Phone: 317.569.4288

***@***.***D735BD.DDC44EC0]

**Comment by nacartwright** [comment]
So looking at this further – this is the line that gets sent by CCX

audio 48776 RTP/AVP 0 96

But after running through the m.split(‘ ‘) then

m = application 9 TCP/MRCPv2

Seems like it’s not keeping the last two params.



Nathan A. Cartwright
Technical Lead
CDW | Phone: 317.569.4288

***@***.***D735C2.45087A30]

**Comment by nacartwright** [comment]
Here is a the full message sent:
's=Unified Contact Center Express 12.5.1.11001-348',
'c=IN IP4 10.89.219.175',
't=0 0',
'm=audio 49730 RTP/AVP 0 96',
'a=rtpmap:0 pcmu/8000',
'a=rtpmap:96 telephone-event/8000',
'a=fmtp:96 0-15',
'a=recvonly',
'a=mid:1',
'm=application 9 TCP/MRCPv2',
'a=setup:active',
'a=connection:new',
'a=fmtp:96 0-15',
'a=resource:speechsynth',
'a=cmid:1'



Nathan A. Cartwright
Technical Lead
CDW | Phone: 317.569.4288

***@***.***D735C7.C1A57890]

**Comment by MayamaTakeshi** [comment]
OK. I did some changes in the underlying mrcp-utils library.
Please get the latest mrcp_server code and do an 'npm install' to get the changes.

**Comment by nacartwright** [comment]
That seems to have solved that issue.

One last thing is I’m getting this now

2021-04-22 14:58:18.602 error: FB29B2FD-0178-1000-4000-001125AE2A68 (mrcp_server.js:84) setting handler for speechsynth

Nathan A. Cartwright
Technical Lead
CDW | Phone: 317.569.4288

***@***.***D73790.83D23A10]

**Comment by MayamaTakeshi** [comment]
OK. That was just wrong tagging of log using 'error' instead of 'info'. I corrected it now.
